### ISSUE TITLE
Sticky Header, Sticky footer and not space underneath the page-selection

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen-v1#7]
![grafik](https://user-images.githubusercontent.com/15019030/116885751-8847ac80-ac28-11eb-860f-3f5462760935.png)

**Comment by navid-kalaei** [comment]
@wellemut we are safe to close this issue because of the mega issue on [#kartevonmorgen-v1/374](https://github.com/kartevonmorgen/kartevonmorgen/issues/374)
